# -*- coding: utf-8 -*-
"""Generate a paste-ready prompt for a large model to independently audit the
vol1 answer labels. Generic rules only (no specific examples), no leakage of
my own judgment (File B)."""
import json, pathlib, sys, importlib.util

ROOT = pathlib.Path('E:/projects/novelSpeakerV4')
spec = importlib.util.spec_from_file_location('sf', ROOT / 'annotator' / 'score_fixed.py')
sf = importlib.util.module_from_spec(spec); spec.loader.exec_module(sf)

v = 1
novel = (sf.VOL[v] / 'novel.txt').read_text(encoding='utf-8').splitlines()
data = json.loads((ROOT / 'docs' / f'审阅_vol{v}_文件A_待核清单.json').read_text(encoding='utf-8'))
items = data['items']
canon = data['canon']
a1 = [x for x in items if x['kind'] == 'A1']
a2 = [x for x in items if x['kind'] == 'A2']

CTX = 6

def ctx(ln):
    lo, hi = max(1, ln - CTX), min(len(novel), ln + CTX)
    return "\n".join(
        f"{k:>5}{' >>>' if k == ln else '    '} {novel[k-1]}" for k in range(lo, hi + 1))

L = []
L.append("# 任务：小说对话说话人标注 —— 参考答案审核")
L.append("")
L.append("## 背景")
L.append("")
L.append("有一部中文小说（日译中轻小说）的标注任务：把正文中每一处「」引号内的内容，标注出**说话人**。")
L.append("现有两份结果：**参考答案**（人工/历史标注）和**某 AI 模型的标注输出**。二者不一致的条目，")
L.append("需要你审核，判断**哪些是参考答案错了**，并给出原文依据。")
L.append("")
L.append("## 标注规则")
L.append("")
L.append("**A. 说话人归属**")
L.append("1. 引号内容若是某个角色当场说出的话，标该角色。")
L.append("2. 引号内容若是某个角色的内心独白（原文有「心想」「暗自说」「脑海里」等心理动词），归该角色。")
L.append("3. 群体发言 → 标群体名（如某商行的人、某村民群体）。")
L.append("4. 以下情况标 `无人称引语`：")
L.append("   - 纯环境声、动物声、物体声、拟声词")
L.append("   - **被当作语言材料谈论的词句**（原文常出现「这句话」「这两个字」「这个称呼」「单字」等元语言标记）")
L.append("   - 叙述者给神态/姿态配的字幕式引号")
L.append("   - 找不到任何归属主体的引用")
L.append("5. 短语气词、应答词、省略号（如「唔。」「咦？」「……」）**仍是发言**，不要判为无人称引语。")
L.append("")
L.append("**B. 标签写法（重要）**")
L.append("")
L.append("- **有名字的用名字，没有名字的用职业或身份。**")
L.append("  - 若一个角色在原文中有专有名字，必须使用其名字，不要用其称号、绰号、外貌描述或职业。")
L.append("  - 若一个角色没有专有名字（路人、店员、村民等），用原文中最稳定的职业/身份称谓。")
L.append("- 同一角色在全卷应使用**统一的标签**。")
L.append("- 若同一角色在不同段落被原文用不同称谓称呼，仍应统一为该角色的规范标签。")
L.append("")
L.append("**C. 本卷出现的角色规范标签**（由原文整理，供参考）")
L.append("")
L.append("`" + "`、`".join(sorted(canon)) + "`")
L.append("")
L.append("> 说明：以上是原文中可识别的角色/群体。若你认为某处应使用不在此列表中的标签（例如原文出现的其他人名或群体），")
L.append("> 也可以使用，但必须在依据里说明。")
L.append("")
L.append("## 输入说明")
L.append("")
L.append(f"共 **{len(items)}** 条待审条目，分两类：")
L.append("")
L.append(f"- **A1（{len(a1)} 条）**：参考答案与模型输出**不一致**。请判断是参考答案错、还是模型错，还是两者都不对。")
L.append(f"- **A2（{len(a2)} 条）**：参考答案写了**多个并列标签**（表示当时认为写其中任一都算对）。")
L.append("  按规则 B（有名字用名字），请裁定一个**唯一**的规范标签。")
L.append("")
L.append("每条条目给出：D 编号、所在行号、引语原文、参考答案、模型输出、原文上下文（`>>>` 标记该引语所在行）。")
L.append("")
L.append("## 输出要求")
L.append("")
L.append("**对每一条输出一行**，格式：")
L.append("")
L.append("```")
L.append("D编号|判定|正确标签|依据")
L.append("```")
L.append("")
L.append("字段说明：")
L.append("")
L.append("- **判定**（A1 条目填）：`答案对` / `答案错` / `存疑`")
L.append("  - `答案对`：参考答案的归属正确（即模型输出错）")
L.append("  - `答案错`：参考答案的归属错误")
L.append("  - `存疑`：原文证据不足以判断")
L.append("- **判定**（A2 条目填）：直接填 `裁定`")
L.append("- **正确标签**：你认为正确的唯一说话人标签。若确实无法归属，填 `无人称引语`；")
L.append("  若证据不足，填 `?`。")
L.append("- **依据**：引用原文中支持你判断的**具体字句**（简短，10-30 字），必须能在原文中找到。")
L.append("")
L.append("**注意事项**：")
L.append("")
L.append("1. **只依据原文判断**，不要因为某个答案来自「参考答案」或「模型」就偏向任何一方。两者都可能错。")
L.append("2. 必须输出**全部**条目，不得省略、不得合并。")
L.append("3. 不要输出任何解释性文字或代码块，只输出上述格式的行。")
L.append("4. 若某条你判断参考答案错、但模型的输出也不对，判定仍填 `答案错`，并在「正确标签」里给出你的答案。")
L.append("")
L.append("---")
L.append("")
L.append(f"# 待审条目（共 {len(items)} 条）")
L.append("")
L.append(f"## A1 参考答案与模型不一致（{len(a1)} 条）")
L.append("")
for x in a1:
    L.append(f"### D{x['d']:04d}（第 {x['line']} 行）")
    L.append("")
    L.append(f"- 引语：{x['quote']}")
    L.append(f"- 参考答案：`{' / '.join(x['answer'])}`")
    L.append(f"- 模型输出：`{x['model'] or '(空)'}`")
    L.append("")
    L.append("```")
    L.append(ctx(x['line']))
    L.append("```")
    L.append("")

L.append(f"## A2 参考答案多标签，需裁定唯一标签（{len(a2)} 条）")
L.append("")
for x in a2:
    L.append(f"### D{x['d']:04d}（第 {x['line']} 行）")
    L.append("")
    L.append(f"- 引语：{x['quote']}")
    L.append(f"- 参考答案（多标签）：`{' / '.join(x['answer'])}`")
    L.append(f"- 模型输出：`{x['model'] or '(空)'}`")
    L.append("")
    L.append("```")
    L.append(ctx(x['line']))
    L.append("```")
    L.append("")

text = "\n".join(L)
p = ROOT / 'docs' / f'审阅_vol{v}_给大模型的prompt.md'
p.write_text(text, encoding='utf-8')
print(f'已写出 {p}')
print(f'  长度 {len(text)} 字符，约 {len(text)//2} tokens（中文粗估）')
print(f'  A1 {len(a1)} 条 + A2 {len(a2)} 条 = {len(items)} 条')
